[workspace]
authors = ["Miguel Villa Floran <miguel.villafloran@gmail.com>"]
channels = ["conda-forge"]
name = "hello-world"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
libc = "2.31"

[activation]
env = { PYTHONPATH = "." }

[dependencies]
python = "3.11.*"
pinocchio = "==3.2.0"
hpp-fcl = ">=2.4.0"
numpy = ">=1.24"
cmake = "*"
make = "*"
cxx-compiler = "*"

[pypi-dependencies]
easydict = ">=1.13"
hydra-core = ">=1.3.2"
ipdb = ">=0.13.13"
joblib = ">=1.5.2"
loguru = ">=0.7.3"
loop-rate-limiters = ">=1.2.0"
lxml = ">=6.0.2"
matplotlib = ">=3.10.8"
meshcat = ">=0.3.2"
mujoco = ">=3.4.0"
numpy-stl = ">=3.2.0"
onnx = ">=1.20.0"
onnxruntime = ">=1.23.2"
open3d = ">=0.19.0"
opencv-python = ">=4.11.0.86"
plotly = ">=6.5.0"
pygame = ">=2.6.1"
pynput = ">=1.8.1"
pyyaml = ">=6.0.3"
rich = ">=14.2.0"
scipy = ">=1.16.3"
sshkeyboard = ">=2.3.1"
tensorboard = ">=2.20.0"
termcolor = ">=3.2.0"
tqdm = ">=4.67.1"
unitree-sdk2py = { git = "https://github.com/carlosdp/unitree_sdk2_python.git", branch = "proper-python-modules" }
wandb = ">=0.23.1"
